name: VPA
services:
  VPA:
    image: mwdle/vpa:latest
    container_name: VPA
    restart: unless-stopped
    init: true
    build:
      context: .
      dockerfile: ./Dockerfile

    environment:
      TRUSTED_PROXIES: "172.16.0.0/16"
      APP_TITLE: Virtual Public Artboard
      FILE_NUM_LIMIT: 50
    networks:
      - VPA
    volumes:
      - ${DOCKER_VOLUMES}/VPA/VirtualPublicArtboard:/var/lib/vpa

    read_only: true
    user: "${UID}:${GID}"
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL

    logging:
      driver: "journald"

    deploy:
      resources:
        limits:
          cpus: "0.3"
          memory: 100M
          pids: 25

networks:
  VPA:
    name: VPA
    external: true
