services:
  VPA:
    image: mwdle/vpa:latest
    container_name: <YOUR_CONTAINER_NAME>
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./Dockerfile
    networks:
      - <YOUR_CONTAINER_NETWORK>
    volumes:
      - </YOUR/VPA/DATA/FOLDER>:/VPA # If using FILE_NUM_LIMIT other than 0 (see below), the host folder you select should not contain any extraneous files. Make sure the permissions are set to allow reading and writing to this directory.
    environment:
      - NODE_ENV=production
      - TRUSTED_PROXIES="172.16.0.0/12" # This is used to determine the real IP address of your clients if VPA is behind a reverse proxy. Assumes your reverse proxy is running in a docker container, 172.16.0.0/12 is the subnet range used by docker containers.
      - APP_TITLE=<Your Name> <Public|Private> Artboard # VPA uses the title on the webpage. It also creates an acronym of the provided title for use on the webpage so it is recommended to use at least a two word app title.
      - FILE_NUM_LIMIT=1000 # A limit of 0 means no limit. Every image in 12.24 KB at default resolution of 442x224. A limit of 1000 images yields a storage limit of ~11.95 MB.
    deploy:
      resources:
        limits: # These limits should work fine for most configurations, but may need to be increased if you have a large number of clients.
          cpus: '0.15'
          memory: 20M

networks:
  <YOUR_CONTAINER_NETWORK>: # Assumes you have already created a docker network using 'docker network create <YOUR_CONTAINER_NETWORK_NAME>'
    name: <YOUR_CONTAINER_NETWORK_NAME>
    external: true